### ISSUE TITLE
API User permissions

### ISSUE THREAD

**Issue by jcralbino** [AbsaOSS/external-dns-infoblox-webhook#14]
Hello Team

I was using previously provider of ExternalDNS for Infoblox, it seems that this is the only one that should be used, is that correct?

Can you please confirm the minimum API user permissions for this to work?

Regards
Jose

**Comment by k0da** [comment]
@jcralbino permissions should be pretty much the same.

This webhook is based on what was used to be intree to external-dns with slight refactoring in a way how we handle updates. 

We no longer delete/create record but rather update it

**Comment by jcralbino** [comment]
Thanks for the feedback

What do you mean that you do not create objects?

That was one of the most relevant parts of the tool.
To create dynamically the objects used by a k8s cluster.

Can you elaborate on that decision and if this would be added in the roadmap?

**Comment by k0da** [comment]
Sorry for not to be clear.
On record update, provider no longer recreates a record but updates it.

**Comment by jcralbino** [comment]
Thanks 
I was able to migrate from the previous implementation to this one within issues ( until now )
