### ISSUE TITLE
[feature request] hability to configure basepath of wapi call

### ISSUE THREAD

**Issue by mcarbonneaux** [AbsaOSS/external-dns-infoblox-webhook#18]
What would you like to be added:

can be possible to add new environement variable to permit to set basepath before /wapi like //wapi.

Why is this needed:
i need to use infoblox api behind api gateway, and i'm oblige to add /api before /wapi (/api/wapi), and actualy is not possible to configure infoblox provider to change base path of the /wapi/, like //wapi/.

**Comment by kuritka** [comment]
Hi @mcarbonneaux. Thank you for asking and I agree with you. This is unfortunately hardcoded in [infoblox-go-client](https://github.com/infobloxopen/infoblox-go-client/blob/master/connector.go#L247) and I'm afraid that it cannot be changed in a simple way on our side.

**Comment by mcarbonneaux** [comment]
i've post feature request on infoblox go client her : https://github.com/infobloxopen/infoblox-go-client/issues/238

**Comment by mcarbonneaux** [comment]
i've made pull request : https://github.com/infobloxopen/infoblox-go-client/pull/239

**Comment by kuritka** [comment]
Hi @mcarbonneaux , awesome job! When I have some time, I'll try to see if we can incorporate it on our side. Thank you!

**Comment by kuritka** [comment]
note: @k0da , once https://github.com/infobloxopen/infoblox-go-client/pull/239 has been merged (ideally released) into infoblox-go-client, we will be able to release extended configuration with the basepath.
