### ISSUE TITLE
No new image releases on new version

### ISSUE THREAD

**Issue by aboe76** [AbsaOSS/external-dns-infoblox-webhook#29]
The github action pipeline fails with the new releases, because the goreleaser-action complains about Uppercase in the repo name.
this is because the project name starts with an Uppercase: "AbsaOSS"

see: https://github.com/AbsaOSS/external-dns-infoblox-webhook/actions/runs/12294943844/job/34311229219#step:9:1667

**Comment by kuritka** [comment]
reverted back, see #30
